# Generated by Django 6.0.4 on 2026-05-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0006_rename_date_commande_reservation_date_reservation'),
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailreservation',
            name='livre',
            field=models.ForeignKey(limit_choices_to={'quantite__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='livres.livre'),
        ),
    ]
