# Generated by Django 6.0.4 on 2026-05-09 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0014_merge_20260508_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 24, 8, 56, 44, 800550)),
        ),
    ]
